### ISSUE TITLE
[feature-request] Make `Node` serializable to JSON

### ISSUE THREAD

**Issue by thiskevinwang** [wooorm/markdown-rs#10]
👋 — awesome project here!

I'm not entirely sure if this is actually a helpful method to have, but a `.to_json()` method (or making `Node` serializable to JSON) on `Node` feels like a nice-to-have... 

I'm a rust noob, but I implemented said serialization functionality here in this repo:
https://github.com/thiskevinwang/markdown-rs-test

**Comment by wooorm** [comment]
heyy 👋

Yeah, good idea to add serde-able annotations!

It would be important to match the JSON structure of https://github.com/syntax-tree/mdast though. Particularly to match exactly what https://github.com/syntax-tree/mdast-util-from-markdown exposes too.

**Comment by kyle-mccarthy** [comment]
@wooorm I was looking into implementing Serialize for everything. Should this crate be parsing everything exactly has remark does?

**Comment by wooorm** [comment]
a) What is *everything*?
b) Eh, yeah, at least adhering to `mdast`, where do you want to diverge?

**Comment by kyle-mccarthy** [comment]
@wooorm I may be wrong, but I think that this implementation handles unicode characters differently than the javascript implementation in mdast. 

If you use the [link-reference test](https://github.com/syntax-tree/mdast-util-from-markdown/blob/main/test/fixtures/link-reference.md) and compare the outputs, the start and end points will all be off by 1 after encountering the fancy/smart apostrophe in the word "they're".

I assume this is because JS uses UTF-16 while Rust uses UTF-8, so Rust counts it as 2 where as in JS it's 1.

I have the serialization implemented, but the majority of the tests in `mdast-util-from-markdown` are failing.

**Comment by wooorm** [comment]
You are correct. The positional info is different. This is indeed about how strings are present in the different languages.
It’s not perfect, but it makes some sense, as users do use this information to slice from the input document. In JS, its positional info is useable for that. In rust, these indices are usable.

But, why are you adding tests from `mdast-util-from-markdown`? That project is already implemented and tested here. This issue is about turning the Rust structures into JSON structures?
