### ISSUE TITLE
Syntax tree abstractness

### ISSUE THREAD

**Issue by andrewbaxter** [wooorm/markdown-rs#39]
My impression was that an abstract syntax tree represents the logical/semantic content of a document, rather than formatting specifics.

Since markdown ignores things like single new lines from a rendering perspective, I'd expect those to be removed/normalized out in the ast as well.

I think that could be made clear (i.e. text nodes have newlines, etc), or (ideally) the tree would contain abstract data... maybe as an option

**Comment by ChristianMurphy** [comment]
The mdast functions provide access to the abstract syntax tree.
And yes, mdast does abstract over a fair bit of formatting.
You can read more on that here https://github.com/syntax-tree/mdast#readme

If you have a specific question about mdast feel free to ask in the discussions https://github.com/wooorm/markdown-rs/discussions

The issue tracker is mainly for feature requests and bug reports.
Since this doesn't appear to be either, I'll close it for now.
But feel free to clarify if you do have a specific improvement in mind.

**Comment by andrewbaxter** [comment]
It was a request to make it fully abstract, rather than a weird halfway between abstract and concrete.

**Comment by andrewbaxter** [comment]
I assume you were referring to https://github.com/syntax-tree/mdast#text - that doesn't mention that newlines in the text are not normalized.

**Comment by wooorm** [comment]
I don’t know what you mean with “fully abstract”.

You don’t seem to care about markdown: you care about HTML. Because only when going from markdown to HTML, is it correct that soft line breaks, in certain cases, are “normalized”.
Markdown is not just about HTML. That is why a markdown syntax tree exists. Which is **not** the same as an HTML syntax tree.

In the JavaScript world, you should use [`mdast-util-to-hast`](https://github.com/syntax-tree/mdast-util-to-hast) and then refer to [`hast`](https://github.com/syntax-tree/hast).
This is not yet implemented here in Rust. See the other open issues for more information.

> referring to [syntax-tree/mdast#text](https://github.com/syntax-tree/mdast#text)

Yes, more information about the mdast would go in that project. If you believe the documentation can be improved, please raise a PR/issue there!

**Comment by andrewbaxter** [comment]
I mean abstract as in [abstract syntax](https://en.wikipedia.org/wiki/Abstract_syntax) -- markdown-rs preserves non-semantic information such as newlines in text blocks, so it's more similar to a concrete syntax tree, however other parts (links) return abstract information about the link (i.e. throw away representational information like whether a reference was collapsed or not).

I didn't mean to turn this into a discussion of terminology though -- my point was just that it would be a lot easier to consume if the library decided to be fully abstract (all data is normalized) or fully concrete (user needs to normalize all data), rather than needing to refer to a separate doc for each field I consume (so I'd be totally happy if documentation _isn't_ improved).

You may have misinterpreted some statement of mine, but I'm doing markdown to markdown, so html normalization doesn't help me here.

**Comment by wooorm** [comment]
What would be a lot easier? Perhaps this is an XY problem. It might be good if you can explain what you are actually doing.

Because mdast is in use by millions and millions of users already: this case hasn’t come up before. It would be extremely hard to do.

Have you seen how CommonMark and other CM-compliant markdown parsers handle line endings? https://spec.commonmark.org/dingus/?text=a%0Ab. That line ending is still there.
Browsers just don’t render it.

**Comment by chriskrycho** [comment]
The fact that it is present is also important to allow extensibility using the syntax tree, without requiring every possible extension to be encoded into the AST itself. As an example: pandoc's Markdown supports "poetry"-type blocks, which you write basically like block quotes but with a leading `|` delimiter instead:

```markdown
| Here is my haiku
|   (I admit it is quite bad)
|     But 'twill do for this
```

The resulting output from pandoc is:

```html
<div class="line-block">Here is my haiku<br />
  (I admit it is quite bad)<br />
    But ’twill do for this</div>
```

You can then use a bit of CSS to make `.line-block` render respecting white space (`white-space: pre-wrap`) and 🎉 poetry-ready plain text.

The mdast format does not support that directly, but because the information is preserved (and is not just dropped because HTML will *by default* not respect the white space), you can *recover* it and do post-processing on the AST to support it in your own extension of the parser. But note that the "by default" qualifier is super important even in many HTML contexts, since you can force the browser to render it differently, as this example shows!
