### ISSUE TITLE
Add support for wiki links

### ISSUE THREAD

**Issue by rambip** [wooorm/markdown-rs#62]
First, I'm thankfull for this fantastic work ! 
I'm trying to build a web app to render markdown coming from [obsidian](obsidian.md) or similar software, but there is one feature I'm missing: wikilinks.

It would be nice if I could get `[[article_name|click here]]` blocks in the abstract syntax tree, because it is quite common now in some tools that use markdown.

One potential challenge is that there is no "right answer" to create an html equivalent to this type of link, it depends on the situation.

Would that make sense to add wiki-style links as an option for the abstract syntax tree if there is no way to compile it ? Maybe creating a html link to `./article` would be the best default to convert `[[article]]` ?

Thank's

**Comment by rambip** [comment]
Well, I think at least internal wikilinks are pretty standard: Either you use `[[article_name|url or display]]` or just `[[article_name]]`
But I agree, other kinds of links like interwiki are a mess.

But your're right, there is no spec for that kind of syntax, except the wikipedia one that is not markdown-based.

I will need to find a workaround, maybe replacing the wikilinks by real markdown-style links beforhand

**Comment by ChristianMurphy** [comment]
As a not standardized feature, I don't think this will land in core `markdown-rs`, closing this as not planned.

That said, if parser plugins become a thing https://github.com/wooorm/markdown-rs/issues/32#issuecomment-1344648061, wikilinks could potentially be added as a community extension/plugin instead of a preprocessing step.

If you have interest in extending `markdown-rs` feel free to contribute to the plugin support efforts @rambip!
